mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: xingishere_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults
